services:
  - type: web
    name: plate-app
    env: node
    buildCommand: cd frontend && npm ci && npm run build && cd ../backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: MONGODB_URI
        sync: false
