services:
  - type: web
    name: plate-app
    env: node
    buildCommand: ./build.sh
    startCommand: cd backend && npm start
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: MONGODB_URI
        sync: false
